import { pgEnum } from "drizzle-orm/pg-core"

export const keyStatus = pgEnum("key_status", ['default', 'valid', 'invalid', 'expired'])
export const keyType = pgEnum("key_type", ['aead-ietf', 'aead-det', 'hmacsha512', 'hmacsha256', 'auth', 'shorthash', 'generichash', 'kdf', 'secretbox', 'secretstream', 'stream_xchacha20'])
export const factorType = pgEnum("factor_type", ['totp', 'webauthn'])
export const factorStatus = pgEnum("factor_status", ['unverified', 'verified'])
export const aalLevel = pgEnum("aal_level", ['aal1', 'aal2', 'aal3'])
export const codeChallengeMethod = pgEnum("code_challenge_method", ['s256', 'plain'])
export const equalityOp = pgEnum("equality_op", ['eq', 'neq', 'lt', 'lte', 'gt', 'gte', 'in'])
export const action = pgEnum("action", ['INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'ERROR'])
export const status = pgEnum("Status", ['todo', 'inProgress', 'done', 'canceled'])
export const label = pgEnum("Label", ['bug', 'feature', 'enhancement', 'documentation'])
export const priority = pgEnum("Priority", ['low', 'medium', 'high'])
export const userRole = pgEnum("UserRole", ['user', 'admin', 'superAdmin'])
export const menuStatus = pgEnum("MenuStatus", ['active', 'inactive'])
export const menuType = pgEnum("MenuType", ['menu', 'button', 'dir'])
export const theme = pgEnum("Theme", ['light', 'dark', 'system'])
